### PR TITLE
Setting css extract bundle filename

### PR DESCRIPTION
**Pull request by hbobenicio**
MiniCssExtractPlugin is the actual responsible for setting the name of the CSS extract (and not OptimizeCssAssetsWebpackPlugin). The default value is the bundle name value (which, when not set, defaults to `main`, so thats why it was generated as `main.css`).

This PR sets it to `style.min.css` as expected.

Any other concerns about the `inline: false` OptimizeCssAssetsWebpackPlugin workaround in order to get proper source maps + optimization + extraction?

### CODE REVIEW

**Comment by pldg** [comment]
I'd already tested that, even with `filename: '[name].[contenthash].css'`.

I run another test now, doesn't work.

In both cases the source map is pointing to the bundle css instead of the source css.

**Comment by hbobenicio** [comment]
Interesting... Here it seems to be working normally. Maybe I'm missing something...

**Comment by hbobenicio** [comment]
Here is what I get:

`index.html`:

```html
<link href="style.min.css" rel="stylesheet">
```

`style.min.css`:

```css
body{background-color:#add8e6}h1{color:#f08080}
/*# sourceMappingURL=style.min.css.map */
```

At the `Style Editor` on Firefox Quantum, when inspecting `style.min.css` I get the original source code:
```css
body {
  background-color: lightblue;
}

/* this comment should be elminitated by cssnano / OptimizeCSSAssetsPlugin */

h1 {
  color: lightcoral;
}
```

You see something different from this? Or this is not the expected to happen?

**Comment by pldg** [comment]
If I set *MiniCssExtractPlugin* `filename: style.min.css` I see exactly the same as your screenshot. 

The original source code is **not** inside `style.min.css` but it's inside `style.css`, therefor you should see `style.css` as name reference in the source map.

## Another example

Without setting `filename` (if you use the actual repository as it is) you'll see this by inspecting `index.html` with Chrome:

source-map-bug

Same thing happen, source map reference to `main.css`, but the source code is inside `style.css`.

**Comment by hbobenicio** [comment]
Uhmm... I think I got it now. You intend to have the original source ode inside the bundle as a comment, right?

This is the difference: In my case, I want it really separate. In your case, you want it to be inline. But we both need the source maps.

I've changed this:

```javascript
      new OptimizeCSSAssetsPlugin({
        cssProcessorOptions: {
          map: {
            inline: false // <===
          }
        }
      })
```

into this:

```javascript
      new OptimizeCSSAssetsPlugin({
        cssProcessorOptions: {
          map: {
            inline: true // <===
          }
        }
      })
```

and the original source code appears to be present:

`main.css` (only, with original source inline as comments):

```css
body{background-color:#add8e6}h1{color:#f08080}
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm1haW4uY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBLEtBQ0Usd0JBQTRCLENBQzdCLEFBSUQsR0FDRSxhQUFrQixDQUNuQiIsImZpbGUiOiJtYWluLmNzcyIsInNvdXJjZXNDb250ZW50IjpbImJvZHkge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiBsaWdodGJsdWU7XG59XG5cbi8qIHRoaXMgY29tbWVudCBzaG91bGQgYmUgZWxtaW5pdGF0ZWQgYnkgY3NzbmFubyAvIE9wdGltaXplQ1NTQXNzZXRzUGx1Z2luICovXG5cbmgxIHtcbiAgY29sb3I6IGxpZ2h0Y29yYWw7XG59XG4iXX0= */
```

**Comment by hbobenicio** [comment]
The interesting here is that, if you just leave _OptimizeCssAssetsPlugin_ without `cssProcessorOptions.map` property like this:

```javascript
      new OptimizeCSSAssetsPlugin({})
```

it will not produce source maps **at all** (neither inline nor as a separate file are generated).

You must set it in order to get it working (either inline or as a separate file), with:

```javascript
      new OptimizeCSSAssetsPlugin({
        cssProcessorOptions: {
          map: {
            inline: true
            // or inline: false, depending on your case...
          }
        }
      })
```

**Comment by pldg** [comment]
Name reference is still incorrect.

I don't know how to explain better then this.

I'd already tried some different scenarios, nothing is working.

[postcss source maps options](https://github.com/postcss/postcss/blob/master/docs/source-maps.md#options).

Anyway, *OptimizeCSSAssetsPlugin* should generate correct source maps out of the box (without additional configuration). I hope the core contributors of this plugin will fix this bug soon.

**Comment by hbobenicio** [comment]
Which version of Chrome are you using? Desperate attempt: did you cleared the cache?

**Comment by hbobenicio** [comment]
"Anyway, OptimizeCSSAssetsPlugin should generate correct source maps out of the box (without additional configuration)"

Totally agreed. I hope so too!

**Comment by hbobenicio** [comment]
I'm feeling totally dummy and blind right now... 

"the point is that source map name reference to main.css, but the source code is inside style.css"

I see now the issue you're talking about! Sorry, I was totally blind about it. Got your point... gonna see if I find another workaround to fix it them...

**Comment by hbobenicio** [comment]
I'm gonna close this PR. We can still discuss this on some Issue, but this definitely isn't the right way to fix it.

**Pull request closed without merging**
